import '../../api/client_personal_info/methods';
import '../../api/client_health_info/methods';
import '../../api/client_all_info/methods';
import '../../api/client_weight_info/methods';
import '../../api/client_payment_info/methods';
import '../../api/client_consent/methods';
import '../../api/users/publications';
import '../../api/client_bef_aft_pictures/s3_picture_storage';
import '../../api/client_bef_aft_pictures/publications';
// import '../../api/client_bef_aft_pictures/methods';
