export const SAVE_CLIENT_PERSONAL_INFO = 'SAVE_CLIENT_PERSONAL_INFO';
export const INITIALIZE_NEW_CLIENT = 'INITIALIZE_NEW_CLIENT';
export const SAVE_CLIENT_HEALTH_INFO = 'SAVE_CLIENT_HEALTH_INFO';
export const LOAD_CLIENT_ALL_INFO = 'LOAD_CLIENT_ALL_INFO';
export const SAVE_CLIENT_WEIGHT_INFO = 'SAVE_CLIENT_WEIGHT_INFO';
export const SAVE_CLIENT_PAYMENT_INFO = 'SAVE_CLIENT_PAYMENT_INFO';
